otrrentapi/ui/views.py
""" flask imports """
from flask import (
    render_template, 
    Blueprint, 
    session, 
    request,
    g,
    redirect,
    url_for
    )
from flask_wtf import FlaskForm
from wtforms import (
    BooleanField, 
    StringField, 
    PasswordField, 
    IntegerField,
    SelectField,
    validators
    )
from wtforms.widgets import PasswordInput

""" configuration """
from config import config, log
from helpers.helper import Message, test_ftpconnection, safe_cast
import os
from datetime import datetime
from functools import wraps

""" import & Init storage """
from azurestorage.wrapper import StorageTableCollection
from azurestorage.queuemodels import PushMessage, PushVideoMessage
from azurestorage.tablemodels import Recording, Torrent, User, History
from azurestorage import db
from azurestorage import queue

db.register_model(User())
db.register_model(History())
db.register_model(Recording())
db.register_model(Torrent())
queue.register_model(PushMessage())
queue.register_model(PushVideoMessage())


""" define blueprint """
otrrentui = Blueprint('ui', __name__, template_folder='templates', url_prefix = '/ui')

""" Settings wtf Forms """
class Settings(FlaskForm):
    PushVideo = BooleanField('Video pushen?')

    OtrUser = StringField('OTR User', validators=[validators.Email()])
    OtrPassword = StringField('OTR Password', widget=PasswordInput(hide_value=False))
    UseCutlist = BooleanField('Schnittliste verwenden?')
    #UseSubfolder = BooleanField('Use Cutlist for decoding?')

    Protocol = SelectField('Protokoll', validators=[validators.DataRequired()], choices=[('ftp', 'ftp'),('sftp', 'sftp')])
    Server = StringField('ftp Server', [validators.DataRequired()])
    Port = IntegerField('Port', [validators.DataRequired()])
    FtpUser = StringField('ftp User', [validators.DataRequired(), validators.Length(min=5, max=35)])
    FtpPassword = StringField('ftp Password', widget=PasswordInput(hide_value=False))
    ServerPath = StringField('Pfad', [validators.DataRequired(), validators.Length(min=1, max=35)])

    EMailEndpoint = StringField('EMail Endpoint', validators=[validators.Email()])


@otrrentui.before_request
def beforerequestlogic():

    """ parse request data """
    if not 'platform' in session:
        platform = str.lower(request.args.get('cordovaplatform', request.user_agent.platform))
        if not platform in ['android','ios']:
            session['platform'] = config['APPLICATION_UI_DEFAULT']
        else:
            session['platform'] = platform

    if not 'clientid' in session:
        session['clientid'] = request.args.get('clientid', config['APPLICATION_CLIENT_ID'])
    
    if not 'deviceuuid' in session:    
        session['deviceuuid'] = request.args.get('deviceuuid', '')

    g.platform =  session['platform']
    g.clientid =  session['clientid']
    g.deviceuuid = session['deviceuuid']

    """ user = default """
    g.user = None


    """ message """
    messageid = safe_cast(request.args.get('messageid', 0), int)
    g.message = Message()
    g.message.text = 'Entschuldigung! Diese Funktion wird noch entwickelt und steht in dieser Verion von otrrent noch nicht zu Verfügung.'
    
    if messageid == 1:
        g.message.header = 'Bewerten Sie otrrent'
        g.message.error = True    
        g.message.show = True
    
    elif messageid == 2:
        g.message.header = 'Nutzen Sie otrrent Werbefrei!'
        g.message.error = True    
        g.message.show = True

    elif messageid == 3:
        g.message.header = 'Nutzen Sie otrrent als Pro-User!'
        g.message.error = True    
        g.message.show = True

    elif messageid == 4:
        g.message.header = 'Fehler'
        g.message.text = 'Bitte nutzen Sie die otrrent App! Sie sind nicht eingelogged'
        g.message.error = True    
        g.message.show = True

    elif messageid == 5:
        g.message.header = 'Konfiguration'
        g.message.text = 'Bitte pflegen Sie Ihren Endpoints für torrent oder Videodateien'
        g.message.error = True    
        g.message.show = True


""" decorators """
def login_required(backtoindex=False):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):

            if g.deviceuuid == '' or g.clientid == '':
                g.user = None

            else:
                loginuser = db.get(User(PartitionKey=g.clientid, RowKey=g.deviceuuid))

                """ user exists ? Create a new and  """
                if not db.exists(loginuser):
                    loginuser.created = datetime.now()
                    db.insert(loginuser)
            
                """ login user """
                g.user = loginuser

            if backtoindex and not g.user:
                return redirect(url_for('ui.index', messageid=4))
            else:
                return func(*args, **kwargs)

        return wrapper
    return decorator


#
# ------------------------------------------------------------------------------------------------------------------------
#            
@otrrentui.route('/')
def index():
    """ retrieve top recordings with filters """
       
    #get toplist
    toplist = StorageTableCollection('recordings', "PartitionKey eq 'top'")
    toplist = db.query(toplist)
    toplist.sort(key = lambda item: item.beginn, reverse = True)

    for item in toplist:
        item['startdate'] = item.beginn.strftime('%d.%m.%Y')
        item['starttime'] = item.beginn.strftime('%H:%M')
        item['previewimagelink'] = item['previewimagelink'].replace('http://','https://',1)
        if not 'torrentCount' in item:
            item['torrentCount'] = 0


    """ render platform template """
    pathtemplate = g.platform + '/' + 'index.html'
    return render_template(pathtemplate, title = 'OTR Top Aufnahmen', pagetitle='index', items=toplist,
                            message=g.message)

#
# ------------------------------------------------------------------------------------------------------------------------
#
@otrrentui.route('/<int:epgid>', methods=['GET', 'POST'])
@login_required(False)
def details(epgid):
    """ request top recording detail data """

    """ logging """
    log.info('select all details for recording: {!s} with method {!s}'.format(epgid, request.method))

    """ determine template & messages """
    pathtemplate = g.platform + '/' + 'details.html'

    #get message
    message = g.message
    g.pop('message')

    """ retrieve recording from storage """
    recording = db.get(Recording(PartitionKey = 'top', RowKey = str(epgid)))

    """ show details including all torrents """
    if not db.exists(recording):
        return index()

    recording.Torrents = db.query(recording.Torrents)
    recording.startdate = recording.beginn.strftime('%d.%m.%Y')
    recording.starttime = recording.beginn.strftime('%H:%M')
    recording.previewimagelink = recording.previewimagelink.replace('http://','https://',1)

    if request.method == 'POST':

        """ retrieve Form Data """
        data = request.form.to_dict()
        log.debug(data)

        """ post method = push only available for logged in users """
        if not g.user:
            message.show = True
            message.error = True
            message.header = 'Fehler'
            message.text = 'Bitte loggen Sie sich ein!'
        
        elif (not g.user.ProUser) and (g.user.PushVideo):
            message.show = True
            message.error = True
            message.header = 'Fehler'
            message.text = 'Um Videos zu decodieren müssen Sie Pro Status haben!'

        elif ExistsHistory(g.user.RowKey, epgid): 
            """ already in History ? """
            message.show = True
            message.error = True
            message.header = 'Fehler'
            message.text = 'Sie haben diese Aufnahme bereits erfolgreich gepushed!'

        elif (g.user.PushVideo):
            """ successfully configured ? """
            if not g.user.FtpConnectionChecked:
                return redirect(url_for('ui.settings', messageid=5))


            """ push video """
            job, errormessage = PushVideo(epgid, data['Resolution'], data['TorrentFile'], data['TorrentLink'], g.user) 
            if not job:
                message.show = True
                message.error = True
                message.header = 'Fehler'
                message.text = errormessage
            else:
                """ success """
                message.show = True
                message.header = 'Erfolg'
                message.text = '{!s} wird heruntergeladen, decodiert und danach an Ihren Endpoint gepushed. Die Aufgabe {!s} wurde dazu erfolgreich angelegt'.format(job.sourcefile, job.id)
                
                """ add history """
                AddHistory(g.user, 
                           job.id, 'video', epgid, 
                           recording.beginn, recording.sender, recording.titel, recording.genre, recording.previewimagelink, data['Resolution'], 
                           job.sourcefile,
                           request.remote_addr, request.user_agent.platform,
                           request.user_agent.browser,
                           request.user_agent.version,
                           request.user_agent.language)                          

        else:
            """ successfully configured ? """
            if not g.user.FtpConnectionChecked:
                return redirect(url_for('ui.settings', messageid=5))

            """ push torrent """
            job, errormessage = PushTorrent(epgid, data['Resolution'], data['TorrentFile'], data['TorrentLink'], g.user) 
            if not job:
                message.show = True
                message.error = True
                message.header = 'Fehler'
                message.text = errormessage
            else:
                """ success """
                message.show = True
                message.header = 'Erfolg'

otrrentapi/ui/templates/android/_layout.html
<!DOCTYPE html>
<html>

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>otrrent</title>
    <!-- Path to Framework7 Library CSS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/framework7.material.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/framework7.material.colors.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/material-icons.css') }}">

    <!-- Goggle Adsense: Page Ads-->
    {% if not g.user.AdsRemoved %}
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6230052197390545",
            enable_page_level_ads: true
        });
    </script>
    {% endif %}

    {% endblock %}

</head>

<body class="theme-green">

    <!-- Panels overlay-->
    <div class="panel-overlay"></div>

    <!-- Left panel with panel-cover effect-->
    <div class="panel panel-left panel-cover">
        <div class="view navbar-fixed">
            <div class="pages">
                <div data-page="panel-left" class="page">
                    <div class="navbar">
                        <div class="navbar-inner">
                            <div class="center">otrrent</div>
                        </div>
                    </div>
                    <div class="page-content">

                        <div class="content-block-title">Menü</div>
                        <div class="list-block">
                            <ul>
                                <li>
                                    <a href="{{ url_for('ui.history') }}" class="item-link item-content close-panel" data-ignore-cache="true">
                                        <div class="item-media"><i class="material-icons">history</i></div>
                                        <div class="item-inner item-title">Verlauf</div>
                                    </a>
                                </li>
                                <li>
                                    <a id="settings" href="{{ url_for('ui.settings') }}" class="item-link item-content close-panel" data-ignore-cache="true">
                                        <div class="item-media"><i class="material-icons">settings</i></div>
                                        <div class="item-inner item-title">Einstellungen</div>
                                    </a>
                                </li>
                                {% if not g.user.AdsRemoved %}
                                <li>
                                    <a id="adsfree" href="{{ url_for('ui.about') }}?messageid=2" class="item-link item-content close-panel">
                                        <div class="item-media"><i class="material-icons">notifications_off</i></div>
                                        <div class="item-inner item-title">Werbefrei</div>
                                    </a>
                                </li>
                                {% endif %}
                                {% if not g.user.ProUser %}
                                <li>
                                    <a id="getprouser" href="{{ url_for('ui.about') }}?messageid=3" class="item-link item-content close-panel">
                                        <div class="item-media"><i class="material-icons">person_add</i></div>
                                        <div class="item-inner item-title">Pro User</div>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>

                        <div class="content-block-title">App</div>
                        <div class="list-block">
                            <ul>
                                <li>
                                    <a id="privacy" href="{{ url_for('www.index') }}#privacy" target="_blank" class="item-link item-content close-panel external">
                                        <div class="item-media"><i class="material-icons">lock</i></div>
                                        <div class="item-inner item-title">Datenschutzerklärung</div>
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ url_for('ui.about') }}" class="item-link item-content close-panel">
                                        <div class="item-media"><i class="material-icons">info</i></div>
                                        <div class="item-inner item-title">Über</div>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Views-->
    <div class="views">

        <!-- Your main view, should have "view-main" class-->
        <div class="view view-main">


            <!-- Pages, because we need fixed-through navbar and toolbar, it has additional appropriate classes-->
            <div class="pages navbar-fixed">
                <!-- Page, data-page contains page name-->
                <div data-page="{{ pagetitle }}" class="page">

                    <!-- Top Navbar-->
                    {% block navbar %}
                    <div class="navbar">
                        <div class="navbar-inner">

                            <!-- We have home navbar without left link-->
                            <div class="center sliding">{{ title }}</div>
                            <div class="right">
                                <!-- Right link contains only icon - additional "icon-only" class--><a href="#" class="link icon-only open-panel"> <i class="icon icon-bars"></i></a>
                            </div>

                        </div>
                    </div>
                    {% endblock %}

                    <!-- Search Bar -->
                    {% block searchbar %}
                    {% endblock %}

                    <!-- Scrollable page content-->
                    <div class="page-content">

                        <!-- Alerts -->
                        {% if message.show %}
                        <div class="content-block inset">
                            <div class="content-block-inner {% if message.error %}bg-pink color-white{% else %}bg-green{% endif %}">
                                <strong>{{ message.header}}</strong>
                                <p>{{ message.text}}</p>
                                {% if message.code != 0 %}<p class="color-gray">{{ message.code}}</p>{% endif %}
                            </div>

                        </div>
                        {% endif %}


                        {% block content %}
                        {% endblock %}

                    </div>
                </div>
            </div>


        </div>
    </div>

    <!-- Path to Framework7 Library JS-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/framework7.min.js') }}"></script>

    <!-- Path to your app js-->
    <script type="text/javascript" src="{{ url_for('static', filename='js/framework7.myandroidapp.js') }}"></script>


    {% if 'authtoken' in session and session['deviceuuid'] is none %}

    <!-- Cookie Disclaimer-->
    <script>
        if (!sessionStorage.cookiedisclaimershown) {
            myApp.pickerModal('.picker-info')
        }
    </script>


    {% endif %}



</body>
</html>

otrrentapi/ui/templates/android/about.html
{% extends "android/_layout.html" %}

{% block navbar%}
<div class="navbar">
    <div class="navbar-inner">
        <div class="left"><a href="#" class="back link"> <i class="icon icon-back"></i></a></div>
        <div class="center sliding">{{ title }}</div>
        <div class="right">
            <!-- Right link contains only icon - additional "icon-only" class--><a href="#" class="link icon-only open-panel"> <i class="icon icon-bars"></i></a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<!-- Über -->
<div id="about" class="card">
    <div class="card-header">otrrent</div>
    <div class="card-content-inner">
        <p>
            Mit <strong>otrrent</strong> können Nutzer von <a href="http://www.onlinetvrecorder.com/" target="_blank" class="external">onlineTVrecorder.com</a> (OTR) per torrent verfuegbare beliebteste Aufnahmen von OTR auswaehlen und die entsprechende torrent Datei an einen heimischen ftp-Server weiterleiten.
            Am heimischen Rechner kann dann mit einem bittorrent Client die entsprechende Sendung als otrkey-Datei runtergeladen werden. <strong>otrrent</strong> benötigt für die Weiterleitung der torrent Datei die Zugangsdaten zu Ihrem ftp-Server.
        </p>

        <p>
            Als otrrent <strong>Pro-User</strong> können Sie Aufnahmen in der otrrent-Cloud decodieren, schneiden und dann als Video an Ihren ftp-Server senden lassen.
            Um diese Funktion nutzen zu können, ist ein Nutzeraccount unter <a href="http://www.onlinetvrecorder.com/" target="_blank" class="external">onlineTVrecorder.com</a> (OTR) notwendig. otrrent benötigt Ihre OTR Zugangsdaten um die von Ihnen aufgenommenen Sendungen decodieren zu können.
            Ihre Zugangsdaten werden verschlüsselt übertragen und gespeichert. Ihre Daten werden nicht weitergegeben und nur zum decodieren der von Ihnen ausgewählten Sendungen genutzt. In dieser Verion steht diese Funktion noch nicht zu Verfügung.
        </p>
        <p>
            otrrent wird sich in nachfolgenden Versionen über <strong>Werbung</strong> finanzieren. Es wird aber eine Funktion geben otrrent ohne Werbung zu nutzen! Diese Funktion wird aber noch entwickelt
            und steht in dieser Version noch nicht zu Verfügung.
        </p>
    </div>
</div>

<!-- Hinweise & Lizenzen -->
<div id="about" class="card">
    <div class="card-header">Lizenzen &amp; rechtliche Hinweise</div>
    <div class="card-content-inner">
        <p>Die <strong>Inhalte</strong> dieser App - insbesondere EPG, Top-Aufnahmen &amp; Torrents - sind Eigentum von <a href="http://www.onlinetvrecorder.com/" target="_blank" class="external">onlineTVrecorder.com</a> der Internet TV AG, Seychelles. Alle Rechte liegen bei der Internet TV AG. Diese App zeigt die Daten unverfälscht an.</p>
        <p>Die <strong>otrkey Dateien</strong> sind verschlüsselt und können nur decodiert werden, wenn Sie als OTR Nutzer die Sendung vor Ausstrahlung,&nbsp;wie in einem Videorecorder, programmiert haben.</p>
        <p><strong>Framework7</strong>. otrrent nutzt <a href="https://framework7.io/" target="_blank" class="external">Framework7</a> um als Web App ein natives Nutzergefühl auf android und iOS Geräten zu ermöglichen.</p>
        <p><strong>Fingerprint2</strong>. otrrent nutzt zur Erkennung des Gerätes die Javascript Bibliothek <a href="https://github.com/Valve/fingerprintjs2" target="_blank" class="external">Fingerprint2</a> unter MIT Lizenz. Unter dem Fingerprint speichert otrrent die Einstellungen und der Verlauf (Historie) in der Cloud.</p>
        <p><strong>dAKirby309</strong>. Das Logo der otrrent app unterliegt der  <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank" class="external">CC Attribution 3.0  Unported</a> Lizenz und wurde ursprünglich erstellt von <a href="http://dakirby309.deviantart.com/" target="_blank" class="external">dAKirby309</a></p>
    </div>
</div>

<!-- App Konfiguration -->
<div class="card">
    <div class="card-header">App</div>
    <div class="card-content" id="appconfig">
        <div class="list-block media-list">
            <ul>
                <li class="item-content">
                    <div class="item-inner">
                        <div class="item-subtitle">Version</div>
                        <div class="item-text">{{ config['APPLICATION_VERSION'] }}</div>
                    </div>
                </li>
                <li class="item-content">
                    <div class="item-inner">
                        <div class="item-subtitle">Autor</div>
                        <div class="item-text"><a href="https://app-workshop.de/" target="_blank" class="external">app workshop UG (haftungsbeschränkt)</a></div>
                    </div>
                </li>
                <li class="item-content">
                    <div class="item-inner">
                        <div class="item-subtitle">UI</div>
                        <div class="item-text">{{ g.platform }}</div>
                    </div>
                </li>
                <li class="item-content">
                    <div class="item-inner">
                        <div class="item-subtitle">Plattform</div>
                        <div class="item-text">{{ request.user_agent.platform }}</div>
                    </div>
                </li>
                <li class="item-content">
                    <div class="item-inner">
                        <div class="item-subtitle">Browser</div>
                        <div class="item-text">{{ request.user_agent.browser }}</div>
                    </div>
                </li>
                <li class="item-content">
                    <div class="item-inner">
                        <div class="item-subtitle">Device UUID</div>
                        <div class="item-text">{{ g.deviceuuid }}</div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

otrrentapi/ui/templates/android/details.html
{% extends "android/_layout.html" %}

{% block navbar%}
<div class="navbar">
    <div class="navbar-inner">
        <div class="left"><a href="#" class="back link"> <i class="icon icon-back"></i></a></div>
        <div class="center sliding">{{ title }}</div>
        <div class="right">
            <!-- Right link contains only icon - additional "icon-only" class--><a href="#" class="link icon-only open-panel"> <i class="icon icon-bars"></i></a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- Content Block Details -->

<!-- Details card -->
<div class="content-block-title">{{ item.titel }}</div>
<style>
    .recording-header-pic .card-header {
        height: 40vw;
        background-size: cover;
        background-position: center;
    }

    .button {
        display: block;
        width: 100%;
    }
</style>

<div class="card recording-header-pic">
    <div style="background-image:url({{ item.previewimagelink }})" valign="bottom" class="card-header color-white no-border">
        {{ item.titel }}<br />
        {{ item.genre }}
    </div>

    <div class="card-content">
        <div class="card-content-inner">
            <p>{{ item.text }}</p>
        </div>
    </div>

    <div class="card-footer">
        <p class="color-gray">{{ item.sender }} {{ item.startdate}} {{ item.starttime}}</p>
        <p>
            <i class="material-icons">star</i>
            <i class="material-icons">star</i>
            <i class="material-icons">star</i>
            {% if item.rating == 'hoch' %}
            <i class="material-icons">star</i>
            <i class="material-icons">star_border</i>
            {% elif item.rating == 'sehr hoch' %}
            <i class="material-icons">star</i>
            <i class="material-icons">star</i>
            {% else %}
            <i class="material-icons">star_border</i>
            <i class="material-icons">star_border</i>
            {% endif %}
        </p>
    </div>
</div>


<!-- Torrents Card -->
<div class="card">
    <div class="card-header">Torrents</div>
    <div class="card-content-inner">
        {% for torrent in item.Torrents %}
        <form action="{{ url_for('ui.details', epgid=item.Id) }}" method="POST" class="ajax-submit" style="width:100%; display:block;">
            <input type="hidden" name="Resolution" value="{{ torrent.Resolution }}">
            <input type="hidden" name="TorrentFile" value="{{ torrent.TorrentFile }}">
            <input type="hidden" name="TorrentLink" value="{{ torrent.TorrentLink }}">
            <p>
                <button type="submit" name="{{ torrent.Resolution }}" class="button button-big button-fill button-raised">
                    {% if torrent.Resolution == 'HD' %}
                    <div class="chip">
                        <div class="chip-media bg-orange">{{ torrent.Resolution }}</div>
                        <div class="chip-label">mpg.HD.avi.</div>
                    </div>
                    {% elif torrent.Resolution == 'HQ' %}
                    <div class="chip">
                        <div class="chip-media bg-red">{{ torrent.Resolution }}</div>
                        <div class="chip-label">mpg.HQ.avi.</div>
                    </div>
                    {% elif torrent.Resolution == 'HD.AC3' %}
                    <div class="chip">
                        <div class="chip-media bg-orange">HD</div>
                        <div class="chip-label">mpg.HD.ac3.</div>
                    </div>
                    {% elif torrent.Resolution == 'MP4' %}
                    <div class="chip">
                        <div class="chip-media bg-green">{{ torrent.Resolution }}</div>
                        <div class="chip-label">mpg.mp4.</div>
                    </div>
                    {% else %}
                    <div class="chip">
                        <div class="chip-media bg-blue">{{ torrent.Resolution }}</div>
                        <div class="chip-label">.mpg.avi.</div>
                    </div>
                    {% endif %}

                    {% if torrent.loaded >= torrent.finished %}
                    <div class="chip">
                        <div class="chip-media bg-blue">{{ torrent.loaded }}</div>
                        <div class="chip-label">geladen</div>
                    </div>
                    {% else %}
                    <div class="chip">
                        <div class="chip-media bg-blue">{{ torrent.finished }}</div>
                        <div class="chip-label">fertig</div>
                    </div>
                    {% endif %}

                </button>
            </p>
        </form>
        {% endfor %}
    </div>
</div>

    {% endblock %}

otrrentapi/ui/templates/android/index.html
{% extends "android/_layout.html" %}

{% block searchbar %}
<!-- Search Bar -->
<form data-search-list=".list-block-search" data-search-in=".item-title" class="searchbar searchbar-init">
    <div class="searchbar-input">
        <input type="search" placeholder="Suche"><a href="#" class="searchbar-clear"></a>
    </div>
</form>
{% endblock %}

{% block content %}

<!-- This block will be displayed if nothing found -->
<div class="content-block searchbar-not-found">
    <div class="content-block-inner">Nichts gefunden</div>
</div>

<!-- Content Block Listview -->
<div class="list-block media-list list-block-search searchbar-found">

    <ul>

        {% for item in items %}

        {% if loop.changed(item.startdate) %}
        <!-- Divider -->
        <li class="item-divider">{{ item.startdate }}</li>


        {% if not g.user.AdsRemoved %}
        <!-- Ads after Divider -->
        <li class="item-content">
            <div class="item-inner" style="margin-top:5px; margin-bottom:5px; margin-right:5px;">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-format="fluid"
                     data-ad-layout-key="-fd-s+7c-3c-k4"
                     data-ad-client="ca-pub-6230052197390545"
                     data-ad-slot="1160467221"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
        </li>
        {% endif %}

        {% endif %}

        <!-- Listitems -->
        <li>
            <a href="{{ url_for('ui.details', epgid=item.Id) }}" class="item-link item-content">
                <div class="item-media"><img data-src="{{ item.previewimagelink }}" class="lazy" width="80"></div>
                <div class="item-inner">
                    <div class="item-title-row">
                        <div class="item-title">{{ item.titel }}</div>
                        {% if item.torrentCount > 0 %}
                        <div class="item-after">
                            <span class="chip-media {% if item.torrentCount >= 3 %}bg-red{% elif item.torrentCount == 2%}bg-orange{% else %}bg-blue{% endif %}">
                                {{ item.torrentCount }}
                            </span>
                        </div>
                        {% endif %}
                    </div>
                    <div class="item-subtitle">{{ item.genre }}</div>
                    <div class="item-text">
                        {{ item.sender }} {{ item.startdate }} {{ item.starttime }}
                    </div>

                </div>
            </a>
        </li>

        {% endfor %}

    </ul>
</div>

{% endblock %}